import { ImageItem } from './types';

export const INITIAL_IMAGES: ImageItem[] = [
  {
    id: 'img-1',
    title: 'Emerald Lake reflections',
    category: 'Nature',
    url: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Lukasz Szmigiel',
    photographerUrl: 'https://unsplash.com/@szmigieldesign',
    description: 'A serene mountain lake with smooth morning mist reflecting a glowing emerald forest during a vibrant alpine sunrise.',
    location: 'Bavarian Alps, Germany',
    date: 'September 14, 2025',
    camera: 'Canon EOS R5',
    aperture: 'f/8.0',
    shutter: '1/4s',
    iso: 'ISO 100',
    likes: 342,
  },
  {
    id: 'img-2',
    title: 'Bamboo Sanctuary',
    category: 'Nature',
    url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Walter Chang',
    photographerUrl: 'https://unsplash.com/@wrchng',
    description: 'Crisp morning rays filter through towering stalks of green bamboo, casting long elegant geometric shadows on the tranquil earth path.',
    location: 'Arashiyama Grove, Kyoto, Japan',
    date: 'April 22, 2025',
    camera: 'Fujifilm X-T4',
    aperture: 'f/4.0',
    shutter: '1/125s',
    iso: 'ISO 400',
    likes: 198,
  },
  {
    id: 'img-3',
    title: 'Yasaka Pagoda Twilight',
    category: 'Architecture',
    url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Sorin Gheorghita',
    photographerUrl: 'https://unsplash.com/@soringheorghita',
    description: 'The ancient five-story wooden pagoda silhouetted against a dreamy lavender twilight sky as warm streetlights illuminate cobblestone lanes.',
    location: 'Higashiyama, Kyoto, Japan',
    date: 'November 10, 2025',
    camera: 'Sony α7R V',
    aperture: 'f/2.8',
    shutter: '1/15s',
    iso: 'ISO 800',
    likes: 512,
  },
  {
    id: 'img-4',
    title: 'Minimalist concrete haven',
    category: 'Architecture',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    photographer: 'R-Architecture',
    photographerUrl: 'https://unsplash.com/@rarchitecture',
    description: 'An architectural study of concrete, warm oak cladding, and floor-to-ceiling glass paneling converging under golden hour light.',
    location: 'Malibu Coast, California',
    date: 'January 28, 2026',
    camera: 'Hasselblad X2D',
    aperture: 'f/5.6',
    shutter: '1/60s',
    iso: 'ISO 64',
    likes: 276,
  },
  {
    id: 'img-5',
    title: 'The Curious Red Panda',
    category: 'Animals',
    url: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Joshua J. Cotten',
    photographerUrl: 'https://unsplash.com/@joshuacotten',
    description: 'A close-up vertical portrait of a red panda showing off its brilliant orange fur and curious whiskers on an moss-laden branch.',
    location: 'Sichuan Reserves, China',
    date: 'March 05, 2026',
    camera: 'Nikon Z9',
    aperture: 'f/2.8',
    shutter: '1/800s',
    iso: 'ISO 640',
    likes: 423,
  },
  {
    id: 'img-6',
    title: 'Majestic Siberian Tiger',
    category: 'Animals',
    url: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Dušan Veverkolog',
    photographerUrl: 'https://unsplash.com/@veverkolog',
    description: 'An striking gaze of a Siberian tiger peering calmly from the shade, highlighting its deep orange and black striped coat.',
    location: 'Amur Reserve, Siberia',
    date: 'December 18, 2025',
    camera: 'Canon EOS R3',
    aperture: 'f/4.0',
    shutter: '1/500s',
    iso: 'ISO 200',
    likes: 689,
  },
  {
    id: 'img-7',
    title: 'Azure Maldives Reef',
    category: 'Travel',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Sean Oulashin',
    photographerUrl: 'https://unsplash.com/@oulashin',
    description: 'Crystal-clear turquoise waves kissing a pristine white sand shoreline bordered by swaying green coconut palms under a bright morning sky.',
    location: 'Baa Atoll, Maldives',
    date: 'October 02, 2025',
    camera: 'Sony α7 IV',
    aperture: 'f/8.0',
    shutter: '1/1000s',
    iso: 'ISO 100',
    likes: 310,
  },
  {
    id: 'img-8',
    title: 'Balloons over Cappadocia',
    category: 'Travel',
    url: 'https://images.unsplash.com/photo-1527838832700-50592524df7e?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Alex Azabache',
    photographerUrl: 'https://unsplash.com/@alexazabache',
    description: 'Hundreds of colourful hot air balloons ascending concurrently over the dramatic rock valleys of Cappadocia at the first light of spring.',
    location: 'Cappadocia, Turkey',
    date: 'May 01, 2025',
    camera: 'Nikon Z7 II',
    aperture: 'f/4.5',
    shutter: '1/320s',
    iso: 'ISO 200',
    likes: 457,
  },
  {
    id: 'img-9',
    title: 'Gourmet Wood-Fired Pizza',
    category: 'Food',
    url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Ivan Torres',
    photographerUrl: 'https://unsplash.com/@ivantorres',
    description: 'A bubbling, freshly made Neapolitan pizza with blistered crust, rich red tomato sauce, melted mozzarella, and fragrant green basil leaves.',
    location: 'Naples, Italy',
    date: 'July 15, 2025',
    camera: 'Sony α7R III',
    aperture: 'f/2.0',
    shutter: '1/160s',
    iso: 'ISO 160',
    likes: 185,
  },
  {
    id: 'img-10',
    title: 'Rustic Summer Tart',
    category: 'Food',
    url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Brooke Lark',
    photographerUrl: 'https://unsplash.com/@brookelark',
    description: 'A delightful overhead table spread of gourmet dessert, focusing on a home-baked berry pie dusted with sweet powder sugar and mint.',
    location: 'Paris, France',
    date: 'August 09, 2025',
    camera: 'Canon EOS 5D Mark IV',
    aperture: 'f/2.8',
    shutter: '1/125s',
    iso: 'ISO 320',
    likes: 247,
  },
  {
    id: 'img-11',
    title: 'Studio Portrait in Natural Light',
    category: 'Portraits',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Christopher Campbell',
    photographerUrl: 'https://unsplash.com/@obgynco',
    description: 'A striking headshot capturing profound, clean, high-contrast lighting that details natural skin textures in sharp resolution.',
    location: 'Brooklyn, New York',
    date: 'November 22, 2025',
    camera: 'Sony α1',
    aperture: 'f/1.8',
    shutter: '1/250s',
    iso: 'ISO 100',
    likes: 602,
  },
  {
    id: 'img-12',
    title: 'The Elderly Blacksmith',
    category: 'Portraits',
    url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80',
    photographer: 'Joseph Gonzalez',
    photographerUrl: 'https://unsplash.com/@josephgonzalez',
    description: 'A high-contrast side-profile portrait of a master artisan smith, showing lines of wisdom, experience, and character under warm window light.',
    location: 'Toledo, Spain',
    date: 'September 03, 2025',
    camera: 'Nikon Z9',
    aperture: 'f/2.0',
    shutter: '1/200s',
    iso: 'ISO 400',
    likes: 318,
  }
];
